{
 "title": "Monitoramento aplicação",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memória utilizada pelo servidor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(\r\n  ((server_memory_total_bytes - server_memory_available_bytes) / server_memory_total_bytes) * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(server_cpu_usage_percent)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memória utilizada pela aplicação",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "process_private_memory_bytes/ 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Média da Quantidade de Requisição por Status ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "floor(sum(increase(http_requests_by_status_custom[5m])) by (status_code, job))",
     "legendFormat": "{{job}} - {{status_code}} "
    }
   ]
  },
  {
   "title": "Latência por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint!=\"\"}[5m])) by (job, endpoint)\r\n/\r\nsum(rate(http_request_duration_seconds_count{endpoint!=\"\"}[5m])) by (job, endpoint) * 1000",
     "legendFormat": "{{job}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Quantidade de Requisição",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_requests_by_status_custom[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}