apiVersion: apps/v1
kind: Deployment
metadata:
  name: daoapi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: daoapi
    spec:
      containers:
      - name: daoapi
        image: gustascarvalho/dao_api:latest
        ports:
        - containerPort: 3100
        env:
        - name: CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
                name: db-config
                key: CONNECTION_STRING
  selector:
    matchLabels:
        app: daoapi
