{
 "title": "Monitoramento aplicação",
 "time": { "from": "2025-07-15T21:03:07.930Z", "to": "2025-07-15T21:13:07.930Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memória utilizada pelo servidor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((server_memory_total_bytes - server_memory_available_bytes) / server_memory_total_bytes) * 100\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumo de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memória utilizada pela aplicação",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "process_private_memory_bytes/ 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Média da Quantidade de Requisição por Status ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "floor(sum(increase(http_requests_by_status_custom[5m])) by (status_code))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint!=\"\"}[5m])) by (endpoint) /\r\nsum(rate(http_request_duration_seconds_count{endpoint!=\"\"}[5m])) by (endpoint) * 1000",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}