apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastro-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadastro-api
  template:
    metadata:
      labels:
        app: cadastro-api
    spec:
      containers:
        - name: cadastro-api
          image: gustascarvalho/cadastro_api:1.0  # ou substitua com imagem certa
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080