{
 "title": "Monitoramento aplicação",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Memória utilizada pelo servidor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((server_memory_total_bytes - server_memory_available_bytes) / server_memory_total_bytes) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "server_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latência por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) by (endpoint) / sum(rate(http_request_duration_seconds_count[5m])) by (endpoint)\r\n * 1000",
     "legendFormat": "{{endpoint}}Latência"
    }
   ]
  },
  {
   "title": "Média da Quantidade de Requisição por Status ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[5m])) by (code)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de requisições no período ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total[$__interval]))\r\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}