name: Block Pushes to Main

on:
  push:
    branches:
      - master

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - name: Block Push
        run: |
          echo "Push direto para a branch 'master' não é permitido."
          exit 1
