name: Unit Test and Test integration Microservices

on:
  push:
    branches:
      - Microservices
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.302

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal TechChallenge.UnitTests/
          - name: Run Integration Tests
      run: dotnet test --no-build --verbosity normal TechChallenge.IntegrationTest/
