jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0' # Altere para a versão correta do seu projeto

      - name: Install dependencies
        run: dotnet restore

      - name: Run tests with coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults/ \
            /p:CoverletOutput=TestResults/coverage.opencover.xml \
            /p:CoverletOutputFormat=opencover

      - name: Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.projectKey=grupo-tech-challenge_grupo-tech-challenge-v2
            -Dsonar.organization=grupo-tech-challenge
            -Dsonar.coverageReportPaths=TestResults/coverage.opencover.xml
